services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    ports:
      - "3333:3333"
    volumes:
      - .:/app
    environment:
      CACHE_STORE: redis
      QUEUE_CONNECTION: redis
      DB_CONNECTION: pgsql
      DB_USERNAME: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      SEED_DB: true
      REDIS_CLIENT: phpredis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "300"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  test:
    image: registry.dev.hugyourcustomer.ai/huglabs/php8.2-ci:latest
    working_dir: /app
    command: tail -f /dev/null
    stdin_open: true
    tty: true
    environment:
      APP_ENV: testing
    volumes:
      - .:/app
    networks:
      - network


  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_DATABASE:-poc_sjp}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    networks:
      - network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d poc_sjp"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
