[supervisord]
user=root
loglevel=info
pidfile=/var/run/supervisord.pid
nodaemon=true
silent=true
minfds=1024
minprocs=200
logfile=/dev/fd/1
logfile_maxbytes=0

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[program:octane]
process_name=%(program_name)s_%(process_num)02d
command=php /app/artisan octane:start --server=swoole --host=0.0.0.0 --port=3333 --workers=2 --task-workers=2 --max-requests=1000
user=root
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
startsecs=5
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
user=root
autostart=true
autorestart=true
